name: PHP Composer
on:
  push:
    branches:
    - master
    paths:
    - api/**
    - css/**
    - fonts/**
    - img/**
    - .well-known/assetlinks.json
    - browserconfig.xml
    - favicon.ico
    - composer.json
    - manifest.json
    - app-ads.txt
    - robots.txt
    - '**.htaccess'
    - '**.html'
    - '**.css'
    - '**.js'
    - '**.php'
    - '**.xml'
    - '**.png'
    - '**.svg'
    - '**.pdf'

env:
  PRODUCTION_USERNAME: ${{ secrets.SSH_PRODUCTION_USERNAME }}
  PRODUCTION_HOST: ${{ secrets.SSH_PRODUCTION_HOST }}
  PRODUCTION_STAGING_DIR_PATH: ${{ secrets.SSH_PRODUCTION_STAGING_DIR_PREFIX }}website
  TESTING_USERNAME: ${{ secrets.SSH_TESTING_USERNAME }}
  TESTING_HOST: ${{ secrets.SSH_TESTING_HOST }}
  TESTING_STAGING_DIR_PATH: ${{ secrets.SSH_TESTING_STAGING_DIR_PREFIX }}website
  ARTIFACT_NAME: website.tgz

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies using Composer
      run: composer install --prefer-dist --no-progress

    - name: Bundle relevant files into gzipped tar
      # create a gzipped tar which preserves file permissions
      run: |
        mkdir build
        tar czf build/$ARTIFACT_NAME -X tar-exclude.lst .

    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: Send build artifact to prod-server
      run: |
        ssh $PRODUCTION_USERNAME@$PRODUCTION_HOST "mkdir -p $PRODUCTION_STAGING_DIR_PATH && cd $PRODUCTION_STAGING_DIR_PATH && rm *.tgz -f"
        scp build/$ARTIFACT_NAME $PRODUCTION_USERNAME@$PRODUCTION_HOST:$PRODUCTION_STAGING_DIR_PATH

    - name: Send build artifact to test-server
      run: |
        ssh $TESTING_USERNAME@$TESTING_HOST "mkdir -p $TESTING_STAGING_DIR_PATH && cd $TESTING_STAGING_DIR_PATH && rm *.tgz -f"
        scp build/$ARTIFACT_NAME $TESTING_USERNAME@$TESTING_HOST:$TESTING_STAGING_DIR_PATH
